[exercise-7] class photos
testagrossa/algo pull request #11
Opened 2022-06-10 23:33 UTC by Daguis

2022-06-15 13:35 UTC, Daguis commented
la viste asi hago el merge?

2022-06-24 22:16 UTC, testagrossa requested changes

2022-06-24 22:16 UTC, testagrossa commented on exercises/7-class-photos/main.cpp
> +    auto actual = SolutionA::classPhotos(redShirtHeights, blueShirtHeights);
replace this variable with outputA

2022-06-24 22:28 UTC, testagrossa approved these changes

2022-06-24 22:38 UTC, testagrossa requested changes

2022-06-24 22:38 UTC, testagrossa commented on README.md
> -```
why removed this ?

2022-06-24 22:39 UTC, testagrossa approved these changes

2022-06-24 22:40 UTC, testagrossa requested changes
CI is broken

2022-06-24 22:46 UTC, merged